language: php

git:
  depth: 2

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.1
      env: LINT=true
    - php: 7.0
      env: DISABLE_XDEBUG=true
    - php: 5.6
      env: DISABLE_XDEBUG=true
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

notifications:
  email: false

before_script:
  - if [[ $DISABLE_XDEBUG = true ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer dump-autoload --optimize

script:
  # Use custom script to avoid the risk of terminating the build process
  - ./bin/travis/fail-non-feature-topic-branch-pull-request
  # Verify coding standard compliance only once
  - if [[ $LINT = true ]]; then
      composer cm:cs-lint;
    fi
  - if [[ $(( $TRAVIS_BUILD_NUMBER % 25 )) = 0 ]]; then
      composer cm:test-all;
    else
      composer cm:test;
    fi
